name:                bruijn
version:             0.1.0.0
github:              "githubuser/bruijn"
license:             MIT
author:              "Marvin Borner"
maintainer:          "develop@marvinborner.de"
copyright:           "2022 Marvin Borner"

extra-source-files:
- README.md

data-files:
- config
- std/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/marvinborner/bruijn>

default-extensions:
  - LambdaCase

dependencies:
- base >= 4.7 && < 5
- binary
- bitstring
- bytestring
- containers
- directory
- filepath
- haskeline
- megaparsec
- mtl

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wextra
  - -Werror
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints

executables:
  bruijn:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bruijn

tests:
  bruijn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bruijn
